### PR TITLE
Rewrite StatusView and make AttributedTextView cleaner

### PR DESCRIPTION
**Pull request by alexmodrono**
**Changes Overview**  
This PR makes the following changes:

This PR was mostly focused in making code cleaner for easier maintenance.
- Adds a new namespace – `StatusView` –.
- Replaces `AttributedTextView` with `RenderedText`

**Does this PR fix, close, or implement any issues?**  
- [] This PR closes, fixes, or implements the following issues.

**Pending for review**  
@hyperspacedev/swift-ui

### CODE REVIEW

**Review by alicerunsonfedora — CHANGES_REQUESTED** [review]
I'm encountering multiple errors in SwiftLint when trying to build in both AppCode and Xcode.

image

**Comment by iAlex11** [comment]
So I fixed the warnings SwiftLint showed but I didn't get any errors, and SwiftLint didn't complain about `StatusView.content` not starting with uppercase. Something weird is happening with errors lol

**Comment by alexmodrono** [comment]
I already fixed the SwiftLint errors. You still get some warnings, but I already fixed them on the `data/state-management` branch.

**Review by alicerunsonfedora — APPROVED** [review]
After re-cloning the project, I was able to successfully get the codebase working. Just change the SwiftLint script and we should be set (since my Homebrew install of SwiftLint isn't at the same location as yours):

```
if which swiftlint >/dev/null; then
  swiftlint
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

**Pull request merged**
